In [1]:
import pandas as pd
print("Pandas version:", pd.__version__)

Pandas version: 3.0.6

In [5]:
import os

print("Current folder:", os.getcwd())
print("Files here:", os.listdir())

Current folder: d:\Cynaris\cynaris-internship-vamshika\week-1\day-5
Files here: ['analysis_day5.ipynb']

In [6]:
import os

print("Current folder:", os.getcwd())
print("Files here:", os.listdir())

Current folder: d:\Cynaris\cynaris-internship-vamshika\week-1\day-5
Files here: ['analysis_day5.ipynb']

In [7]:
import os

print(os.getcwd())
print(os.listdir())

d:\Cynaris\cynaris-internship-vamshika\week-1\day-5
['analysis_day5.ipynb']

In [10]:
import pandas as pd
import os

print("Current folder:", os.getcwd())
print("CSV found:", os.path.exists("week-1/day-5/north_sales.csv"))
print("CSV found:", os.path.exists("north_sales.csv"))

Current folder: d:\Cynaris\cynaris-internship-vamshika\week-1\day-5
CSV found: False
CSV found: False

In [12]:
import pandas as pd
from pathlib import Path

csv_path = Path(r"D:\Cynaris\cynaris-internship-vamshika\north_sales.csv")
df = pd.read_csv(csv_path)

print("Dataset loaded successfully!")
print("Shape:", df.shape)
df.head()

Dataset loaded successfully!
Shape: (3, 7)

   id product region  amount   sale_date  quantity  discount
0   1  Laptop  North   85000  2026-01-15         2      0.05
1   5   Phone  North   45000  2026-02-05         4      0.05
2   7  Tablet  North   32000  2026-04-01         2      0.08

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   id         3 non-null      int64
 1   product    3 non-null      str
 2   region     3 non-null      str
 3   amount     3 non-null      int64
 4   sale_date  3 non-null      str
 5   quantity   3 non-null      int64
 6   discount   3 non-null      float64
dtypes: float64(1), int64(3), str(3)
memory usage: 300.0 bytes

In [14]:
df.describe()

             id        amount  quantity  discount
count  3.000000      3.000000  3.000000  3.000000
mean   4.333333  54000.000000  2.666667  0.060000
std    3.055050  27622.454634  1.154701  0.017321
min    1.000000  32000.000000  2.000000  0.050000
25%    3.000000  38500.000000  2.000000  0.050000
50%    5.000000  45000.000000  2.000000  0.050000
75%    6.000000  65000.000000  3.000000  0.065000
max    7.000000  85000.000000  4.000000  0.080000

In [15]:
df["region"].value_counts()

region
North    3
Name: count, dtype: int64

In [16]:
df["product"].value_counts()

product
Laptop    1
Phone     1
Tablet    1
Name: count, dtype: int64

In [17]:
df[["product", "amount", "quantity"]]

  product  amount  quantity
0  Laptop   85000         2
1   Phone   45000         4
2  Tablet   32000         2

In [18]:
df[df["amount"] > 40000]

   id product region  amount   sale_date  quantity  discount
0   1  Laptop  North   85000  2026-01-15         2      0.05
1   5   Phone  North   45000  2026-02-05         4      0.05

In [19]:
df.groupby("product")["amount"].sum()

product
Laptop    85000
Phone     45000
Tablet    32000
Name: amount, dtype: int64

In [20]:
df.isnull().sum()

id           0
product      0
region       0
amount       0
sale_date    0
quantity     0
discount     0
dtype: int64

In [21]:
df_clean = df.dropna()

print("Original rows:", len(df))
print("Rows after cleaning:", len(df_clean))

Original rows: 3
Rows after cleaning: 3

In [22]:
from pathlib import Path

output_path = Path.cwd() / "north_sales_cleaned.csv"
df_clean.to_csv(output_path, index=False)

print("Cleaned dataset saved to:", output_path)
print("Export successful!")

Cleaned dataset saved to: d:\Cynaris\cynaris-internship-vamshika\week-1\day-5\north_sales_cleaned.csv
Export successful!

In [23]:
pd.read_csv(output_path).head()

   id product region  amount   sale_date  quantity  discount
0   1  Laptop  North   85000  2026-01-15         2      0.05
1   5   Phone  North   45000  2026-02-05         4      0.05
2   7  Tablet  North   32000  2026-04-01         2      0.08

In [24]:
print("DAY 5: PANDAS DATA ANALYSIS SUMMARY")
print("-" * 40)
print("Total sales records:", len(df_clean))
print("Total sales amount: ₹", df_clean["amount"].sum())
print("Total units sold:", df_clean["quantity"].sum())
print("Average sale amount: ₹", df_clean["amount"].mean())
print("Products analysed:", df_clean["product"].nunique())
print("Missing values:", df_clean.isnull().sum().sum())

DAY 5: PANDAS DATA ANALYSIS SUMMARY
----------------------------------------
Total sales records: 3
Total sales amount: ₹ 162000
Total units sold: 8
Average sale amount: ₹ 54000.0
Products analysed: 3
Missing values: 0