In [1]:
import pandas as pd

# Create the first DataFrame
employees = pd.DataFrame({
    "employee_id": [1, 2, 3, 4],
    "name": ["Asha", "Rahul", "Priya", "Kiran"],
    "department_id": [101, 102, 101, 103]
})

# Create the second DataFrame
departments = pd.DataFrame({
    "department_id": [101, 102, 104],
    "department": ["Data Science", "HR", "Finance"]
})

# Inner join
inner_join = pd.merge(employees, departments, on="department_id", how="inner")
display(inner_join)

   employee_id   name  department_id    department
0            1   Asha            101  Data Science
1            2  Rahul            102            HR
2            3  Priya            101  Data Science

In [2]:
# Left join
left_join = pd.merge(
    employees, departments,
    on="department_id", how="left"
)
print("LEFT JOIN")
display(left_join)

# Right join
right_join = pd.merge(
    employees, departments,
    on="department_id", how="right"
)
print("RIGHT JOIN")
display(right_join)

# Outer join
outer_join = pd.merge(
    employees, departments,
    on="department_id", how="outer"
)
print("OUTER JOIN")
display(outer_join)

LEFT JOIN

   employee_id   name  department_id    department
0            1   Asha            101  Data Science
1            2  Rahul            102            HR
2            3  Priya            101  Data Science
3            4  Kiran            103           NaN

RIGHT JOIN

   employee_id   name  department_id    department
0          1.0   Asha            101  Data Science
1          3.0  Priya            101  Data Science
2          2.0  Rahul            102            HR
3          NaN    NaN            104       Finance

OUTER JOIN

   employee_id   name  department_id    department
0          1.0   Asha            101  Data Science
1          3.0  Priya            101  Data Science
2          2.0  Rahul            102            HR
3          4.0  Kiran            103           NaN
4          NaN    NaN            104       Finance

In [3]:
# Create a sales DataFrame
sales = pd.DataFrame({
    "region": ["North", "North", "South", "South",
               "East", "East", "North", "South"],
    "product": ["Laptop", "Phone", "Laptop", "Phone",
                "Laptop", "Phone", "Phone", "Laptop"],
    "sales": [50000, 20000, 45000, 25000,
              60000, 30000, 15000, 35000]
})

# Create a pivot table
pivot_table = pd.pivot_table(
    sales,
    values="sales",
    index="region",
    columns="product",
    aggfunc="sum",
    fill_value=0
)

display(pivot_table)

product  Laptop  Phone
region
East      60000  30000
North     50000  35000
South     80000  25000

In [4]:
# Create a wide-format DataFrame
wide_data = pd.DataFrame({
    "region": ["North", "South", "East"],
    "Laptop": [50000, 45000, 60000],
    "Phone": [35000, 25000, 30000]
})

print("Wide Format:")
display(wide_data)

# Convert wide data to long format
long_data = pd.melt(
    wide_data,
    id_vars=["region"],
    var_name="product",
    value_name="sales"
)

print("Long Format:")
display(long_data)

Wide Format:

  region  Laptop  Phone
0  North   50000  35000
1  South   45000  25000
2   East   60000  30000

Long Format:

  region product  sales
0  North  Laptop  50000
1  South  Laptop  45000
2   East  Laptop  60000
3  North   Phone  35000
4  South   Phone  25000
5   East   Phone  30000

In [5]:
# Chain multiple Pandas operations
result = (
    sales
    .query("sales >= 30000")
    .groupby("region", as_index=False)["sales"]
    .sum()
    .sort_values("sales", ascending=False)
)

display(result)

  region  sales
0   East  90000
2  South  80000
1  North  50000